/**
 * ComplianceOS — Breach core utilities (Sprint 5)
 *
 * Pure functions for:
 *   - ref_no generation (year-scoped sequential)
 *   - Dual-clock state (CERT-In 6h + DPB 72h)
 *   - State machine
 *   - Severity helpers (delegates to rules-engine)
 *
 * rule_ref: DPDP Rule 7(2) — 72h DPB report; CERT-In CIRCular 2022 — 6h.
 */

import crypto from "node:crypto";
import {
  scoreBreach,
  type BreachScoreInputs,
  type BreachSeverity,
  BREACH_TIMERS,
} from "@complianceos/rules-engine";

export { scoreBreach };
export type { BreachScoreInputs, BreachSeverity };

// ─── ref_no generation ─────────────────────────────────────────────────────
// Format: BR-YYYY-XXXXXX (per-year sequence, 6-digit). The sequence is
// generated by hashing the UUID for stable in-memory testing; a real DB
// deploy should use a Postgres sequence or `nextval()`.

export function buildRefNo(seq: number, year: number = new Date().getUTCFullYear()): string {
  return `BR-${year}-${seq.toString().padStart(6, "0")}`;
}

export function ephemeralRefNo(id: string): string {
  const seq = parseInt(crypto.createHash("sha1").update(id).digest("hex").slice(0, 6), 16) % 1_000_000;
  return buildRefNo(seq);
}

// ─── Dual-clock state ──────────────────────────────────────────────────────

export interface ClockState {
  due: Date;
  msRemaining: number;
  hoursRemaining: number;
  isOverdue: boolean;
  severity: "ok" | "warn" | "danger" | "overdue";
}

function clockSeverity(hours: number): ClockState["severity"] {
  if (hours < 0) return "overdue";
  if (hours <= 1) return "danger";
  if (hours <= 6) return "warn";
  return "ok";
}

export function computeClockState(due: Date, now: Date = new Date()): ClockState {
  const ms = due.getTime() - now.getTime();
  const hours = ms / (60 * 60 * 1000);
  return {
    due,
    msRemaining: Math.max(0, ms),
    hoursRemaining: Math.max(0, Math.round(hours * 10) / 10),
    isOverdue: ms < 0,
    severity: clockSeverity(hours),
  };
}

export function computeDeadlines(detectedAt: Date): {
  certInDueAt: Date;
  dpbDueAt: Date;
} {
  return {
    certInDueAt: new Date(detectedAt.getTime() + BREACH_TIMERS.CERT_IN_HOURS * 60 * 60 * 1000),
    dpbDueAt: new Date(detectedAt.getTime() + BREACH_TIMERS.DPB_HOURS * 60 * 60 * 1000),
  };
}

// ─── State machine ─────────────────────────────────────────────────────────

export const BREACH_STATUSES = [
  "open", // detected, triage pending
  "investigating",
  "contained",
  "cert_in_filed",
  "dpb_initial_filed",
  "dpb_detailed_filed",
  "principals_notified",
  "closed", // post-mortem signed off
] as const;
export type BreachStatus = (typeof BREACH_STATUSES)[number];

export const BREACH_CATEGORIES = [
  "ransomware",
  "phishing_credential",
  "business_email_compromise",
  "misconfiguration",
  "insider_misuse",
  "lost_device",
  "third_party_vendor",
  "denial_of_service",
  "unauthorised_access",
  "data_leak_disclosure",
  "other",
] as const;
export type BreachCategory = (typeof BREACH_CATEGORIES)[number];

export const CATEGORY_LABELS: Record<BreachCategory, string> = {
  ransomware: "Ransomware",
  phishing_credential: "Phishing / Credential theft",
  business_email_compromise: "Business Email Compromise (BEC)",
  misconfiguration: "Misconfiguration",
  insider_misuse: "Insider misuse",
  lost_device: "Lost / stolen device",
  third_party_vendor: "Third-party vendor breach",
  denial_of_service: "Denial of Service",
  unauthorised_access: "Unauthorised access",
  data_leak_disclosure: "Inadvertent disclosure",
  other: "Other",
};

export const STATUS_LABELS: Record<BreachStatus, string> = {
  open: "Open",
  investigating: "Investigating",
  contained: "Contained",
  cert_in_filed: "CERT-In filed",
  dpb_initial_filed: "DPB initial filed",
  dpb_detailed_filed: "DPB detailed filed",
  principals_notified: "Data principals notified",
  closed: "Closed",
};

// Linear progression; the wizard fans out simultaneously rather than strict order.
const TRANSITIONS: Record<BreachStatus, BreachStatus[]> = {
  open: ["investigating", "contained", "closed"],
  investigating: ["contained", "cert_in_filed", "dpb_initial_filed", "closed"],
  contained: ["cert_in_filed", "dpb_initial_filed", "principals_notified", "closed"],
  cert_in_filed: ["dpb_initial_filed", "principals_notified", "closed"],
  dpb_initial_filed: ["dpb_detailed_filed", "principals_notified", "closed"],
  dpb_detailed_filed: ["principals_notified", "closed"],
  principals_notified: ["closed"],
  closed: [],
};

export function canTransition(from: BreachStatus, to: BreachStatus): boolean {
  return TRANSITIONS[from]?.includes(to) ?? false;
}
